version: '3.8'
services:
  api:
    build: .
    command: uvicorn src.web.api:api --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - S3_BUCKET=sc-risk-reports
      - LANGSMITH_API_KEY=changeme
    depends_on:
      - db
      - redis
  dashboard:
    build: .
    command: streamlit run src/web/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379" 